import { Challenge } from "./generator";

// The template we will export
let json = {
  settlements: {
    "11111111-1111-1111-1111-111111111111": {
      id: "11111111-1111-1111-1111-111111111111",
      key: 0,
      name: "Nomad Camp",
      endeavors: 0,
      survivalLimit: 1,
      population: 4,
      deathCount: 0,
      expansions: {
        core: "all",
        whiteLion: "all",
        screamingAntelope: "all",
        phoenix: "all",
        theButcher: "all",
        kingsMan: "all",
        theHand: "all",
        blackKnight: "all",
        "dragon-king": "all",
        "dung-beetle-knight": "all",
        "flower-knight": "all",
        frogdog: "all",
        gorm: "all",
        "green-knight": "all",
        "lion-god": "all",
        "lion-knight": "all",
        "lonely-tree": "all",
        manhunter: "all",
        pariah: "all",
        redWitches: "all",
        slenderman: "all",
        spidicules: "all",
        sunstalker: "all",
        gamblersChest: "all",
        crimsonCrocodile: "all",
        smogSingers: "all",
        king: "all",
        atnas: "all",
      },
      campaign: "PotLantern",
      innovations: [],
      innovationDeck: [],
      ly: 0,
      inspirationalStatue: "",
      notes: "",
      archived: false,
      principles: {
        newLife: false,
        death: false,
        society: false,
        conviction: false,
      },
      milestones: {},
      quarryShowdowns: [""],
      nemeses: [""],
      defeatedMonsters: [],
      locations: ["shrine", "chimes", "packs", "battlefield", "tools", "fire"],
      globalEndeavors: [],
      settlementEffects: {},
      customStoryEvents: [],
      allCursedItems: [],
      survivorSortOrder: "asc",
      survivorSortAttr: "name",
      customExpansions: {},
      storage: {
        resources: {},
        gear: {
          boneSmith: {
            boneAxe: 0,
            boneBlade: 0,
            boneClub: 0,
            boneDagger: 0,
            boneDarts: 0,
            bonePickaxe: 0,
            boneSickle: 0,
            skullHelm: 0,
          },
          skinnery: {
            bandages: 0,
            rawhideBoots: 0,
            rawhideDrum: 0,
            rawhideGloves: 0,
            rawhideHeadband: 0,
            rawhidePants: 0,
            rawhideVest: 0,
            rawhideWhip: 0,
          },
          organGrinder: {
            driedAcanthus: 0,
            fecalSalve: 0,
            luckyCharm: 0,
            monsterGrease: 0,
            monsterToothNecklace: 0,
            stoneNoses: 0,
          },
          catarium: {
            catEyeCirclet: 0,
            catFangKnife: 0,
            catGutBow: 0,
            clawHeadArrow: 0,
            frenzyDrink: 0,
            kingSpear: 0,
            lionBeastKatar: 0,
            lionHeaddress: 0,
            lionSkinCloak: 0,
            whiskerHarp: 0,
            whiteLionBoots: 0,
            whiteLionCoat: 0,
            whiteLionGauntlet: 0,
            whiteLionHelm: 0,
            whiteLionSkirt: 0,
          },
          stoneCircle: {
            beastKnuckle: 0,
            bloodPaint: 0,
            boneEarrings: 0,
            bossMehndi: 0,
            brainMint: 0,
            elderEarrings: 0,
            lanceOfLonginus: 0,
            screamingBracers: 0,
            screamingCoat: 0,
            screamingHorns: 0,
            screamingLegWarmers: 0,
            screamingSkirt: 0,
            speedPowder: 0,
          },
          plumery: {
            arcBow: 0,
            birdBread: 0,
            bloodSheath: 0,
            bloomSphere: 0,
            crestCrown: 0,
            featherMantle: 0,
            featherShield: 0,
            fingerOfGod: 0,
            hollowSword: 0,
            hollowpointArrow: 0,
            hoursRing: 0,
            phoenixFaulds: 0,
            phoenixGauntlet: 0,
            phoenixGreaves: 0,
            phoenixHelm: 0,
            phoenixPlackart: 0,
            rainbowKatana: 0,
            sonicTomahawk: 0,
          },
          leatherWorker: {
            hunterWhip: 0,
            leatherBoots: 0,
            leatherBracers: 0,
            leatherCuirass: 0,
            leatherMask: 0,
            leatherSkirt: 0,
            roundLeatherShield: 0,
          },
          weaponCrafter: {
            calcifiedZanbato: 0,
            counterweightedAxe: 0,
            scrapBoneSpear: 0,
            scrapDagger: 0,
            scrapLantern: 0,
            scrapRebar: 0,
            scrapSword: 0,
            skullcapHammer: 0,
            whistlingMace: 0,
            zanbato: 0,
          },
          blacksmith: {
            beaconShield: 0,
            dragonSlayer: 0,
            lanternCuirass: 0,
            lanternDagger: 0,
            lanternGauntlets: 0,
            lanternGlaive: 0,
            lanternGreaves: 0,
            lanternHelm: 0,
            lanternMail: 0,
            lanternSword: 0,
            perfectSlayer: 0,
            polishingLantern: 0,
            ringWhip: 0,
            scrapShield: 0,
          },
          barberSurgeon: {
            almanac: 0,
            blueCharm: 0,
            bugTrap: 0,
            firstAidKit: 0,
            greenCharm: 0,
            muskBomb: 0,
            redCharm: 0,
            scavengerKit: 0,
          },
          maskMaker: {
            antelopeMask: 0,
            deathMask: 0,
            godMask: 0,
            manMask: 0,
            phoenixMask: 0,
            whiteLionMask: 0,
          },
          "Rare Gear": {
            adventureSword: 0,
            ancientLionClaws: 0,
            belchingBagpipes: 0,
            blackGauntlet: 0,
            blackKnightBadge: 0,
            boneWitchMehndi: 0,
            butcherCleaver: 0,
            butchersBlood: 0,
            calcifiedJuggernautBlade: 0,
            campingBag: 0,
            chaosElfHat: 0,
            childOfLightning: 0,
            darkWaterPearl: 0,
            darkWaterVial: 0,
            deathCrown: 0,
            deathMehndi: 0,
            deathpact: 0,
            deprivationSkinsuit: 0,
            everburn: 0,
            eyePatch: 0,
            fellbrandt: 0,
            flowerKnightBadge: 0,
            flowerKnightHelm: 0,
            forsakerMask: 0,
            gloomBracelets: 0,
            gloomCream: 0,
            gloomHammer: 0,
            gloomKatana: 0,
            gloomMehndi: 0,
            gloomSheath: 0,
            gloomCoatedArrow: 0,
            glyphOfSolitude: 0,
            goldenPlate: 0,
            grinningVisage: 0,
            hiddenCrimsonJewel: 0,
            hideousDisguise: 0,
            hostroxTheGloaming: 0,
            huntersHeart: 0,
            huskOfDestiny: 0,
            ironHandLeft: 0,
            ironHandRight: 0,
            lanternFestivalHorn: 0,
            lanternFestivalMask: 0,
            lanternFestivalMidi: 0,
            lanternFestivalTop: 0,
            lanternHalberd: 0,
            lanternMehndi: 0,
            lionGodStatue: 0,
            lionKnightBadge: 0,
            lionKnightsLeftClaw: 0,
            lionKnightsRightClaw: 0,
            magnumKnives: 0,
            manhuntersHat: 0,
            muramasa: 0,
            necromancersEye: 0,
            ornateBoneBlade: 0,
            portableWaterphone: 0,
            preservedDogpole: 0,
            raptorWormCollar: 0,
            regalFauldsGC: 0,
            regalGauntletGC: 0,
            regalGreavesGC: 0,
            regalHelmGC: 0,
            regalPlackartGC: 0,
            regalSignetRing: 0,
            regeneratingBlade: 0,
            replicaFlowerSword: 0,
            reverberatingLantern: 0,
            shriekingBow: 0,
            sleepingVirusFlower: 0,
            slenderOvule: 0,
            smogLantern: 0,
            speakerCultKnife: 0,
            steelShield: 0,
            steelSword: 0,
            theWeaver: 0,
            thunderMaul: 0,
            toolBelt: 0,
            trashCrown: 0,
            twilightSword: 0,
            wornBrawlingBow: 0,
            wornSeekingBow: 0,
            wornStrafingBow: 0,
            wrath: 0,
          },
          exhaustedLanternHoard: {
            finalLantern: 0,
            oxidizedBeaconShield: 0,
            oxidizedLanternDagger: 0,
            oxidizedLanternGlaive: 0,
            oxidizedLanternHelm: 0,
            oxidizedLanternSword: 0,
            oxidizedRingWhip: 0,
            survivorsLantern: 0,
          },
          Other: { portcullisKey: 0 },
          "Starting Gear": { bloodyCloth: 0, cloth: 4, foundingStone: 4 },
          Pattern: {
            bloodDrinker: 0,
            boneChibouk: 0,
            bowScab: 0,
            colossalChefsCarver: 0,
            countSandals: 0,
            countTabard: 0,
            countTreukh: 0,
            countVest: 0,
            countWrappings: 0,
            cruelCleaver: 0,
            curseHammer: 0,
            diamondScabKatar: 0,
            discordian: 0,
            domeBuster: 0,
            drumOfHope: 0,
            earlBoots: 0,
            earlJawGuard: 0,
            earlRaiment: 0,
            earlSleeves: 0,
            earlTassets: 0,
            fearSpear: 0,
            grimacingGuillotine: 0,
            halberdScab: 0,
            immortalArm: 0,
            jawSaw: 0,
            knifeScab: 0,
            marchionessBlouse: 0,
            marchionessGloves: 0,
            marchionessGorget: 0,
            marchionessSollerets: 0,
            marchionessTrousers: 0,
            maulScab: 0,
            regalPlume: 0,
            regicider: 0,
            saxe: 0,
            seditioner: 0,
            swordScab: 0,
            unbreakableZanbato: 0,
            violetArmorCharm: 0,
            violetPhoenixFaulds: 0,
            violetPhoenixGuantlets: 0,
          },
          "Seed Pattern": {
            armorsmithsTongs: 0,
            backstabbingStone: 0,
            beastHunterHelm: 0,
            claspingShield: 0,
            cyclopsLedger: 0,
            deathDefier: 0,
            dreamKeeperCowl: 0,
            dreamKeeperKnife: 0,
            eldersAegis: 0,
            fingernailWhip: 0,
            heartseeker: 0,
            hushingHarmonium: 0,
            hypersightVisor: 0,
            imitationButcherMask: 0,
            itemsmithsLens: 0,
            jarngreipr: 0,
            luckyCatFangKnife: 0,
            masamune: 0,
            masterBoneDagger: 0,
            mightyBoneAxe: 0,
            monsterTrophy: 0,
            nekoTwilightArmor: 0,
            ornateRapier: 0,
            piercingClaws: 0,
            plasmaCutter: 0,
            rawhideBandana: 0,
            reaperjaw: 0,
            shadowSkleaver: 0,
            spiteBalm: 0,
            sprinterHelm: 0,
            titheBox: 0,
            trueLanternHalberd: 0,
            weaponsmithsHammer: 0,
          },
          dragonArmory: {
            blastShield: 0,
            blastSword: 0,
            blueCore: 0,
            dragonBelt: 0,
            dragonBiteBolt: 0,
            dragonBoots: 0,
            dragonChakram: 0,
            dragonGloves: 0,
            dragonMantle: 0,
            dragonSkullHelm: 0,
            nuclearKnife: 0,
            nuclearScythe: 0,
            redCore: 0,
            shieldedQuiver: 0,
            talonKnife: 0,
          },
          wetResinCrafter: {
            calcifiedDiggingClaw: 0,
            calcifiedCenturyGreaves: 0,
            calcifiedShoulderPads: 0,
            centuryGreaves: 0,
            centuryShoulderPads: 0,
            dbkErrantBadge: 0,
            diggingClaws: 0,
            rainbowWingBelt: 0,
            elasticHarness: 0,
            scarabCirclet: 0,
            seasonedMonsterMeat: 0,
            theBeetleBomb: 0,
          },
          "Sense Memory": {
            satchel: 0,
            vespertineArrow: 0,
            vespertineBow: 0,
            vespertineCello: 0,
            vespertineFoil: 0,
          },
          outskirts: {
            bloodPack: 0,
            crimsonCrocodileTablet: 0,
            disguiseKit: 0,
            dreadedPack: 0,
            frogdogTablet: 0,
            grimjaw: 0,
            huntingSalve: 0,
            kingTablet: 0,
            phoenixTablet: 0,
            scoutLantern: 0,
            scoutWhistle: 0,
            screamingAntelopeTablet: 0,
            smogSingersTablet: 0,
            stoneFaceCloak: 0,
            verminBellyboots: 0,
            whiteLionTablet: 0,
          },
          froskrafter: {
            acidBombs: 0,
            crestAxe: 0,
            frogdogBoots: 0,
            frogdogMask: 0,
            frogdogSleeves: 0,
            frogdogsuit: 0,
            frogdogVest: 0,
            frogdoggles: 0,
            frogwhistle: 0,
            grappleclaw: 0,
            longClub: 0,
            lureLantern: 0,
            spikedBuckler: 0,
            turboTonic: 0,
            vertebrayonet: 0,
            vigorCapsule: 0,
          },
          tuskWorks: {
            bullchargeShield: 0,
            bullfrogBauble: 0,
            bullfrogBoots: 0,
            bullfrogBracers: 0,
            bullfrogCuirass: 0,
            bullfrogDress: 0,
            bullfrogHalberd: 0,
            bullfrogHelm: 0,
            bullfrogMace: 0,
            bullfrogScimitar: 0,
            heavyFrogLantern: 0,
          },
          gormery: {
            acidToothDagger: 0,
            armorSpikes: 0,
            blackSword: 0,
            gaxe: 0,
            gormentBoots: 0,
            gormentMask: 0,
            gormentSleeves: 0,
            gormentSuit: 0,
            gorn: 0,
            greaterGaxe: 0,
            knuckleShield: 0,
            pulseLantern: 0,
            regenerationSuit: 0,
            ribBlade: 0,
            riotMace: 0,
          },
          gormchymist: {
            healingPotion: 0,
            lifeElixer: 0,
            powerPotion: 0,
            steadfastPotion: 0,
            wisdomPotion: 0,
          },
          "Green Armor": {
            fetosaurus: 0,
            greenBoots: 0,
            greenFaulds: 0,
            greenGloves: 0,
            greenHelm: 0,
            greenPlate: 0,
            griswaldo: 0,
          },
          "Sanguine Extrusion": {
            blackAndRedArmet: 0,
            blackAndRedCuirass: 0,
            blackAndRedGauntlets: 0,
            blackAndRedGreaves: 0,
            blackAndRedTonlet: 0,
            hyperElasticBow: 0,
            hyperElasticShield: 0,
            hyperElasticSword: 0,
            redCloak: 0,
          },
          silkMill: {
            amberEdge: 0,
            amberPoleaxe: 0,
            blueRing: 0,
            bodySuit: 0,
            greenRing: 0,
            hoodedScrapKatar: 0,
            redRing: 0,
            silkBomb: 0,
            silkBoots: 0,
            silkRobes: 0,
            silkSash: 0,
            silkTurban: 0,
            silkWhip: 0,
            silkWraps: 0,
            throwingKnife: 0,
          },
          skyreefSanctuary: {
            cycloidScaleHood: 0,
            cycloidScaleJacket: 0,
            cycloidScaleShoes: 0,
            cycloidScaleSkirt: 0,
            cycloidScaleSleeves: 0,
            denticleAxe: 0,
            inkBloodBow: 0,
            inkSword: 0,
            quiverAndSunstring: 0,
            shadowSalivaShawl: 0,
            skleaver: 0,
            skyHarpoon: 0,
            sunLureAndHook: 0,
            sunsharkArrows: 0,
            sunsharkBow: 0,
            sunspotDart: 0,
            sunspotLantern: 0,
          },
          crimsonCrockery: {
            bloodCompassLantern: 0,
            bloodglassCleaver: 0,
            bloodglassDagger: 0,
            bloodglassKatar: 0,
            bloodglassLongsword: 0,
            bloodglassSaw: 0,
            crimsonBow: 0,
            crimsonDress: 0,
            crimsonFaulds: 0,
            crimsonGuard: 0,
            crimsonHelm: 0,
            crimsonPearls: 0,
            crimsonSlippers: 0,
            crocboneHammer: 0,
            crocodileyes: 0,
            fingerDarts: 0,
            gigglingScythe: 0,
          },
          chorusseum: {
            energyDrum: 0,
            hamfluter: 0,
            harpyHarp: 0,
            peaceDagger: 0,
            pipa: 0,
            razorCymbals: 0,
            singingBoots: 0,
            singingBreastplate: 0,
            singingCap: 0,
            singingGloves: 0,
            singingHeart: 0,
            singingPantaloons: 0,
            spearOfLife: 0,
            spinningSword: 0,
          },
          kingsmith: {
            adjudicator: 0,
            assassinator: 0,
            deathkingBoots: 0,
            deathkingGuantlets: 0,
            deathkingGreaves: 0,
            deathkingHelm: 0,
            deathkingPlatemail: 0,
            grandKingslayer: 0,
            kingslayer: 0,
            royalLantern: 0,
            royalMedallion: 0,
            royalShield: 0,
            usurper: 0,
          },
          armory: {
            blade: 0,
            divider: 0,
            gavel: 0,
            partisan: 0,
            scourge: 0,
          },
        },
      },
      log: [{ t: 1761330342172, m: 71, ly: 0, a: { num: 4 } }],
      loadouts: {},
      pillars: { scout: true, seedPattern: true },
      patterns: [],
      allLocations: [],
      allInnovations: [],
      allProficiencies: [
        "fistandtooth",
        "axe",
        "sword",
        "bow",
        "club",
        "spear",
        "shield",
        "grand",
        "whip",
        "katar",
        "twilight",
        "dagger",
        "scythe",
        "katana",
      ],
      allFightingArts: [
        "tough",
        "lastManStanding",
        "thrillSeeker",
        "monsterClawStyle",
        "tumble",
        "rhythmChaser",
        "crossarmBlock",
        "mightyStrike",
        "strategist",
        "clutchFighter",
        "doubleDash",
        "extraSense",
        "timelessEye",
        "ambidextrous",
        "berserker",
        "leader",
        "crazed",
        "unconciousFighter",
        "oratorOfDeath",
        "comboMaster",
        "synchronizedStrike",
        "scholarOfDeath",
        "redFist",
        "legendaryLungs",
        "zeroPresence",
        "swordsmansPromise",
        "kingOfAThousandBattles",
        "boneWhisperer",
        "lucernaesLantern",
        "graceOfDormenatus",
        "beastOfCaratosis",
        "kingsStep",
        "escapeArtist",
        "feralStrength",
        "piercer",
        "hardheaded",
        "unbreakable",
        "acrobatics",
        "fatedBlow",
        "championsRite",
        "frozenStar",
        "alteredDestiny",
        "carapaceOfWill",
        "propulsionDrive",
        "otherworldlyLuck",
        "feralShout",
        "softLanding",
        "unfroggable",
        "buccalBloodBreathing",
        "sadFrogdogSong",
        "mammothHunting",
        "lureEpilepsy",
        "immovableObject",
        "burningFocus",
        "heroic",
        "ruthless",
        "unrelenting",
        "wardrobeExpert",
        "tenacious",
        "headliner",
        "courtlyScreenwriter",
        "agelessApprentice",
        "abyssalSadist",
        "trailblazer",
        "seasonedHunter",
        "transcendedMasochist",
        "sacredCode",
        "freeclimber",
        "inversion",
        "quadradept",
        "transcendedMasochistRW",
        "storyOfTheForsaker",
        "storyOfTheForged",
        "storyOfTheLibrary",
        "vaultKey",
        "phantomFriend",
        "blottedOut",
        "clarityOfDarkness",
        "vengeance",
        "harvestman",
        "deathTouch",
        "burningAmbition",
        "defender",
        "sneakAttack",
        "purpose",
        "trickAttack",
        "suppressedShadow",
        "godOfCheaters",
        "bloodzerker",
        "glassMask",
        "invigorator",
        "aerialTransfusion",
        "monsterEmpathy",
        "relentless",
        "virtuoso",
        "devilsMelody",
        "mindPalace",
        "firstStep",
        "regicide",
        "actualize",
        "beetleStrength",
        "silkSurgeon",
        "fencing",
        "acanthusDoctor",
        "trueBlade",
        "necromancer",
        "eternalWill",
      ],
      allDisorders: [
        "immortal",
        "vestiphobia",
        "hyperactive",
        "seizures",
        "anxiety",
        "hemophobia",
        "indecision",
        "bingeEating",
        "rageholic",
        "traumatized",
        "quixotic",
        "monsterPanic",
        "hoarder",
        "squeamish",
        "postTraumaticStress",
        "secretive",
        "prey",
        "apathetic",
        "fearOfTheDark",
        "coprolalia",
        "honorable",
        "weakSpot",
        "aichmophobia",
        "dishonorable",
        "maladroit",
        "ptophobia",
        "performanceAnxiety",
        "arithmopihilia",
        "destined",
        "superstitious",
        "motionSickness",
        "verminObsession",
        "ghostlyBeauty",
        "narcissistic",
        "chimericDelusion",
        "delerium",
        "eproctophilia",
        "absentSeizures",
        "megalophobia",
        "enfeebled",
        "delicious",
        "tunnelVision",
        "starkRaving",
        "shallowLungs",
        "stageFright",
        "primaDonna",
        "unlucky",
        "anhedonia",
        "codependent",
        "battleDrunk",
        "cowardice",
        "hyperalgesia",
        "hyperSensitivity",
        "spiralGanglia",
        "controlophobia",
        "revenge",
        "tinyArachnophobia",
        "emotionless",
        "sunDrunk",
        "overprotective",
        "atelophobia",
        "ergophobia",
        "photophilia",
        "somniphobia",
        "bloodlust",
        "phobophobia",
        "brainSmog",
        "pacifist",
        "subjugated",
        "directionalDyslexia",
        "schadenfreude",
        "weltschmerz",
        "flowerAddiction",
      ],
      allAbilities: [
        "acidpalms",
        "analyze",
        "tinker",
        "explore",
        "matchmaker",
        "ageless",
        "bitterFrenzy",
        "blueLifeExchange",
        "burntNerves",
        "caratosis",
        "crystalSkin",
        "dormenatus",
        "dreamOfTheBeast",
        "dreamOfTheCrown",
        "dreamOfTheLantern",
        "fatedBattle",
        "greenLifeExchange",
        "homingInstinct",
        "ironWill",
        "legendcaller",
        "leylineWalker",
        "lifeExchange",
        "lucernae",
        "madOracle",
        "metalMaw",
        "partner",
        "peerless",
        "possessed",
        "redLifeExchange",
        "sourDeath",
        "storyOfTheForsaker",
        "storyOfTheGoblin",
        "storyOfTheYoungHero",
        "sweetBattle",
        "thundercaller",
        "boneWitchScarredEyes",
        "boneWitchWounds",
        "cancerousIllness",
        "endlessBabble",
        "kingsCurse",
        "leprosy",
        "lovelornRock",
        "marrowHunger",
        "twilightSword",
        "stalwart",
        "prepared",
        "spec-fistandtooth",
        "spec-axe",
        "spec-club",
        "spec-sword",
        "spec-dagger",
        "spec-grand",
        "spec-spear",
        "spec-whip",
        "spec-bow",
        "spec-katar",
        "spec-shield",
        "mastery-fistandtooth",
        "mastery-axe",
        "mastery-club",
        "mastery-sword",
        "mastery-dagger",
        "mastery-grand",
        "mastery-spear",
        "mastery-whip",
        "mastery-bow",
        "mastery-katar",
        "mastery-shield",
        "frenzy",
        "deadInside",
        "brokenVow",
        "destructiveVow",
        "largesse",
        "spec-scythe",
        "mastery-scythe",
        "limbMaker",
        "presage",
        "wayOfTheRust",
        "heartOfTheSword",
        "twelveFingers",
        "psychovore",
        "constellationWitch",
        "constellationStorm",
        "constellationSculptor",
        "constellationRust",
        "constellationReaper",
        "constellationGoblin",
        "constellationAbsolute",
        "constellationGambler",
        "iridescentHide",
        "oraclesEye",
        "pristine",
        "gravelGuts",
        "boundingLegs",
        "mereNavi",
        "bullfrogNeck",
        "pubescentVestment",
        "extraLongArms",
        "livingFilmParasites",
        "noNose",
        "thinSkinned",
        "nightmareBlood",
        "nightmareSpurs",
        "nightmareMembrane",
        "superHair",
        "joyless",
        "bileBody",
        "bileSmell",
        "boostHeart",
        "ferrousFeed",
        "fused",
        "heartStrings",
        "oneTwo",
        "sinisterConfusion",
        "sizzlingBlood",
        "warmedUp",
        "perfectKidneys",
        "improbableSurvivor",
        "redStringOfFate",
        "reflexiveShooter",
        "astrocyteExcitation",
        "hyperaemicDefense",
        "forgettable",
        "rivalsScar",
        "childOfTheSun",
        "purified",
        "reflection",
        "refraction",
        "spec-katana",
        "spectralStomach",
        "phototaxis",
        "selfless",
        "murderer",
        "arrogance",
        "dilettante",
        "compelled",
        "spoiled",
        "privileged",
        "unrestrained",
        "important",
        "fixated",
        "frailty",
        "disembodied",
        "ravenous",
        "inferiorityComplex",
        "selfish",
        "sleepless",
        "juiceHunter",
        "songheart",
        "markOfTheCyclopsKnight",
        "grounded",
        "astutePsyche",
        "discourseSavant",
        "radiantPresence",
        "darkCalling",
        "reroller",
        "fortuneSight",
        "fusedFeet",
        "advancedPlay",
        "cutthroat",
        "flipperFeet",
        "foundersEye",
        "gameMaster",
        "levinblood",
        "outrider",
        "stoneCrusher",
        "truePeace",
        "closedMeridians",
        "anemic",
        "hemostasis",
        "astute",
      ],
      allSevereInjuries: [
        "deaf",
        "bleedingKidneys",
        "blind",
        "brokenArm",
        "brokenHip",
        "brokenLeg",
        "brokenRib",
        "bruisedTailbone",
        "collapsedLung",
        "concussion",
        "contracture",
        "destroyedBack",
        "destroyedGenitals",
        "destroyedTooth",
        "disemboweled",
        "dislocatedShoulder",
        "dismemberedArm",
        "dismemberedLeg",
        "gapingChestWound",
        "hamstrung",
        "intestinalProlapse",
        "intracranialHemorrhage",
        "rupturedMuscle",
        "rupturedSpleen",
        "shatteredJaw",
        "slashedBack",
        "spiralFracture",
        "tornAchillesTendon",
        "tornMuscle",
        "warpedPelvis",
      ],
      allSettlementEvents: [],
      allStoryEvents: [],
      allNemesisEncounters: [],
      allShowdowns: [],
      allArmorSets: [
        "rawhide",
        "leather",
        "screaming",
        "phoenix",
        "lantern",
        "whiteLion",
        "earlArmor",
        "marchionessArmor",
        "countArmor",
        "dragon",
        "rolling",
        "frogdogArmor",
        "bullfrogdogArmor",
        "gorment1",
        "gorment2",
        "green",
        "warlord",
        "dancer",
        "brawler",
        "blackAndRedArmor",
        "silk",
        "cycloid",
        "sprinterArmor",
        "beastHunterArmor",
        "imitationButcherArmor",
        "crimsonArmor",
        "singingArmor",
        "deathkingArmor",
      ],
      allWanderers: [],
      allPatterns: [
        "countSandals",
        "countTabard",
        "countTreukh",
        "countVest",
        "countWrappings",
        "earlBoots",
        "earlJawGuard",
        "earlRaiment",
        "earlSleeves",
        "earlTassets",
        "marchionessBlouse",
        "marchionessGloves",
        "marchionessGorget",
        "marchionessSollerets",
        "marchionessTrousers",
        "piercingClaws",
        "claspingShield",
        "grimacingGuillotine",
        "jawSaw",
        "spiteBalm",
        "bowScab",
        "halberdScab",
        "knifeScab",
        "swordScab",
        "maulScab",
        "rawhideBandana",
        "eldersAegis",
        "luckyCatFangKnife",
        "imitationButcherMask",
        "monsterTrophy",
        "sprinterHelm",
        "fingernailWhip",
        "shadowSkleaver",
        "titheBox",
        "cyclopsLedger",
        "beastHunterHelm",
        "hushingHarmonium",
        "itemsmithsLens",
        "armorsmithsTongs",
        "weaponsmithsHammer",
        "ornateRapier",
        "trueLanternHalberd",
        "masamune",
        "jarngreipr",
        "backstabbingStone",
        "masterBoneDagger",
        "heartseeker",
        "deathDefier",
        "mightyBoneAxe",
        "reaperjaw",
        "bloodDrinker",
        "diamondScabKatar",
        "domeBuster",
        "fearSpear",
        "immortalArm",
        "regicider",
        "seditioner",
        "violetArmorCharm",
        "violetPhoenixFaulds",
        "violetPhoenixGuantlets",
        "curseHammer",
        "discordian",
        "drumOfHope",
        "saxe",
      ],
      gameVersion: "1.6",
    },
  },
  survivors: {
    "11111111-1111-1111-1111-111111111111": {
      "00000000-0000-0000-0000-000000000001": {
        name: "Zachary",
        gender: "M",
        departing: true,
        returning: false,
        attributes: {
          MOV: 5,
          STR: 0,
          EVA: 0,
          ACC: 0,
          LCK: 0,
          SPD: 0,
        },
        tempAttributes: {
          MOV: 0,
          STR: 0,
          EVA: 0,
          ACC: 0,
          LCK: 0,
          SPD: 0,
        },
        survival: 1,
        insanity: { value: 0, light: false },
        reroll: false,
        hasReroll: false,
        xp: 0,
        courage: 0,
        understanding: 0,
        weaponProficiency: { weapon: "", rank: 0 },
        armor: {
          head: { value: 0, heavy: false },
          arms: { value: 0, light: false, heavy: false },
          body: { value: 0, light: false, heavy: false },
          waist: { value: 0, light: false, heavy: false },
          legs: { value: 0, light: false, heavy: false },
        },
        survivalActions: {
          dodge: true,
          encourage: false,
          surge: false,
          dash: false,
          endure: false,
        },
        canSpendSurvival: true,
        canGainSurvival: true,
        savior: false,
        canUseFightingArts: true,
        fightingArts: [],
        disorders: [],
        abilities: [],
        severeInjuries: [],
        skipNextHunt: false,
        dead: false,
        causeOfDeath: "",
        timeOfDeath: 0,
        cursedItems: [],
        affinities: { red: 0, blue: 0, green: 0 },
        notes: "",
        retired: false,
        parents: { father: null, mother: null },
        log: [],
        loadout: {
          name: "Zachary",
          gear: [
            [
              { location: "Starting Gear", name: "cloth" },
              { location: "Starting Gear", name: "foundingStone" },
              null,
            ],
            [null, null, null],
            [null, null, null],
          ],
          unsaved: true,
          armorSet: "",
        },
        settlement: "11111111-1111-1111-1111-111111111111",
        id: "00000000-0000-0000-0000-000000000001",
        key: "00000000-0000-0000-0000-000000000001",
      },
      "00000000-0000-0000-0000-000000000002": {
        name: "Allister",
        gender: "M",
        departing: true,
        returning: false,
        attributes: {
          MOV: 5,
          STR: 0,
          EVA: 0,
          ACC: 0,
          LCK: 0,
          SPD: 0,
        },
        tempAttributes: {
          MOV: 0,
          STR: 0,
          EVA: 0,
          ACC: 0,
          LCK: 0,
          SPD: 0,
        },
        survival: 1,
        insanity: { value: 0, light: false },
        reroll: false,
        hasReroll: false,
        xp: 0,
        courage: 0,
        understanding: 0,
        weaponProficiency: { weapon: "", rank: 0 },
        armor: {
          head: { value: 0, heavy: false },
          arms: { value: 0, light: false, heavy: false },
          body: { value: 0, light: false, heavy: false },
          waist: { value: 0, light: false, heavy: false },
          legs: { value: 0, light: false, heavy: false },
        },
        survivalActions: {
          dodge: true,
          encourage: false,
          surge: false,
          dash: false,
          endure: false,
        },
        canSpendSurvival: true,
        canGainSurvival: true,
        savior: false,
        canUseFightingArts: true,
        fightingArts: [],
        disorders: [],
        abilities: [],
        severeInjuries: [],
        skipNextHunt: false,
        dead: false,
        causeOfDeath: "",
        timeOfDeath: 0,
        cursedItems: [],
        affinities: { red: 0, blue: 0, green: 0 },
        notes: "",
        retired: false,
        parents: { father: null, mother: null },
        log: [],
        loadout: {
          name: "Allister",
          gear: [
            [
              { location: "Starting Gear", name: "cloth" },
              { location: "Starting Gear", name: "foundingStone" },
              null,
            ],
            [null, null, null],
            [null, null, null],
          ],
          unsaved: true,
          armorSet: "",
        },
        settlement: "11111111-1111-1111-1111-111111111111",
        id: "00000000-0000-0000-0000-000000000002",
        key: "00000000-0000-0000-0000-000000000002",
      },
      "00000000-0000-0000-0000-000000000003": {
        name: "Lucy",
        gender: "F",
        departing: true,
        returning: false,
        attributes: {
          MOV: 5,
          STR: 0,
          EVA: 0,
          ACC: 0,
          LCK: 0,
          SPD: 0,
        },
        tempAttributes: {
          MOV: 0,
          STR: 0,
          EVA: 0,
          ACC: 0,
          LCK: 0,
          SPD: 0,
        },
        survival: 1,
        insanity: { value: 0, light: false },
        reroll: false,
        hasReroll: false,
        xp: 0,
        courage: 0,
        understanding: 0,
        weaponProficiency: { weapon: "", rank: 0 },
        armor: {
          head: { value: 0, heavy: false },
          arms: { value: 0, light: false, heavy: false },
          body: { value: 0, light: false, heavy: false },
          waist: { value: 0, light: false, heavy: false },
          legs: { value: 0, light: false, heavy: false },
        },
        survivalActions: {
          dodge: true,
          encourage: false,
          surge: false,
          dash: false,
          endure: false,
        },
        canSpendSurvival: true,
        canGainSurvival: true,
        savior: false,
        canUseFightingArts: true,
        fightingArts: [],
        disorders: [],
        abilities: [],
        severeInjuries: [],
        skipNextHunt: false,
        dead: false,
        causeOfDeath: "",
        timeOfDeath: 0,
        cursedItems: [],
        affinities: { red: 0, blue: 0, green: 0 },
        notes: "",
        retired: false,
        parents: { father: null, mother: null },
        log: [],
        loadout: {
          name: "Lucy",
          gear: [
            [
              { location: "Starting Gear", name: "cloth" },
              { location: "Starting Gear", name: "foundingStone" },
              null,
            ],
            [null, null, null],
            [null, null, null],
          ],
          unsaved: true,
          armorSet: "",
        },
        settlement: "11111111-1111-1111-1111-111111111111",
        id: "00000000-0000-0000-0000-000000000003",
        key: "00000000-0000-0000-0000-000000000003",
      },
      "00000000-0000-0000-0000-000000000004": {
        name: "Erza",
        gender: "F",
        departing: true,
        returning: false,
        attributes: {
          MOV: 5,
          STR: 0,
          EVA: 0,
          ACC: 0,
          LCK: 0,
          SPD: 0,
        },
        tempAttributes: {
          MOV: 0,
          STR: 0,
          EVA: 0,
          ACC: 0,
          LCK: 0,
          SPD: 0,
        },
        survival: 1,
        insanity: { value: 0, light: false },
        reroll: false,
        hasReroll: false,
        xp: 0,
        courage: 0,
        understanding: 0,
        weaponProficiency: { weapon: "", rank: 0 },
        armor: {
          head: { value: 0, heavy: false },
          arms: { value: 0, light: false, heavy: false },
          body: { value: 0, light: false, heavy: false },
          waist: { value: 0, light: false, heavy: false },
          legs: { value: 0, light: false, heavy: false },
        },
        survivalActions: {
          dodge: true,
          encourage: false,
          surge: false,
          dash: false,
          endure: false,
        },
        canSpendSurvival: true,
        canGainSurvival: true,
        savior: false,
        canUseFightingArts: true,
        fightingArts: [],
        disorders: [],
        abilities: [],
        severeInjuries: [],
        skipNextHunt: false,
        dead: false,
        causeOfDeath: "",
        timeOfDeath: 0,
        cursedItems: [],
        affinities: { red: 0, blue: 0, green: 0 },
        notes: "",
        retired: false,
        parents: { father: null, mother: null },
        log: [],
        loadout: {
          name: "Erza",
          gear: [
            [
              { location: "Starting Gear", name: "cloth" },
              { location: "Starting Gear", name: "foundingStone" },
              null,
            ],
            [null, null, null],
            [null, null, null],
          ],
          unsaved: true,
          armorSet: "",
        },
        settlement: "11111111-1111-1111-1111-111111111111",
        id: "00000000-0000-0000-0000-000000000004",
        key: "00000000-0000-0000-0000-000000000004",
      },
    },
  },
  timelines: {
    logs: { "11111111-1111-1111-1111-111111111111": [] },
    "11111111-1111-1111-1111-111111111111": [
      {
        settlementEvents: [],
        storyEvents: [],
        nemesisEncounters: [""],
        specialShowdowns: [],
        showdowns: [""],
      },
    ],
  },
  customExpansions: [],
  milestones: {},
  version: "2.49.4",
};

function camelize(str: string) {
  return str
    .replace(/(?:^\w|[A-Z]|\b\w)/g, function (word, index) {
      return index === 0 ? word.toLowerCase() : word.toUpperCase();
    })
    .replace(/\s+/g, "");
}

export function generateScribe(c: Challenge) {
  // update the JSON with the relevant bits
  json.settlements["11111111-1111-1111-1111-111111111111"].endeavors =
    c.survivors.length;
  json.settlements["11111111-1111-1111-1111-111111111111"].survivalLimit =
    c.settlement?.maxSurvival ?? 0;

  const survivorIds = [
    "00000000-0000-0000-0000-000000000001" as keyof (typeof json.survivors)["11111111-1111-1111-1111-111111111111"],
    "00000000-0000-0000-0000-000000000002" as keyof (typeof json.survivors)["11111111-1111-1111-1111-111111111111"],
    "00000000-0000-0000-0000-000000000003" as keyof (typeof json.survivors)["11111111-1111-1111-1111-111111111111"],
    "00000000-0000-0000-0000-000000000004" as keyof (typeof json.survivors)["11111111-1111-1111-1111-111111111111"],
  ];

  for (const k of survivorIds) {
    json.survivors["11111111-1111-1111-1111-111111111111"][
      k
    ].survivalActions.encourage = c.settlement?.encourage ?? false;
    json.survivors["11111111-1111-1111-1111-111111111111"][
      k
    ].survivalActions.dodge = c.settlement?.dodge ?? false;
    json.survivors["11111111-1111-1111-1111-111111111111"][
      k
    ].survivalActions.dash = c.settlement?.dash ?? false;
    json.survivors["11111111-1111-1111-1111-111111111111"][
      k
    ].survivalActions.surge = c.settlement?.surge ?? false;

    json.survivors["11111111-1111-1111-1111-111111111111"][k].survival =
      c.settlement?.startingSurvival ?? 0;
  }

  perSurvivor(survivorIds[0], 0, c);
  perSurvivor(survivorIds[1], 1, c);
  perSurvivor(survivorIds[2], 2, c);
  perSurvivor(survivorIds[3], 3, c);

  // setup monster
  if (c.monster?.nemesis) {
    json.timelines[
      "11111111-1111-1111-1111-111111111111"
    ][0].nemesisEncounters[0] = `${camelize(c.monster.name)}Level${
      c.monster.tier
    }`;
    json.timelines["11111111-1111-1111-1111-111111111111"][0].showdowns.pop();
    json.settlements[
      "11111111-1111-1111-1111-111111111111"
    ].nemeses[0] = `${camelize(c.monster.name)}Level${c.monster.tier}`;
    json.settlements[
      "11111111-1111-1111-1111-111111111111"
    ].quarryShowdowns.pop();
  } else if (c.monster) {
    json.timelines[
      "11111111-1111-1111-1111-111111111111"
    ][0].showdowns[0] = `${camelize(c.monster.name)}Level${c.monster.tier}`;
    json.timelines[
      "11111111-1111-1111-1111-111111111111"
    ][0].nemesisEncounters.pop();
    json.settlements[
      "11111111-1111-1111-1111-111111111111"
    ].quarryShowdowns[0] = `${camelize(c.monster.name)}Level${c.monster.tier}`;
    json.settlements["11111111-1111-1111-1111-111111111111"].nemeses.pop();
  }

  // add gear to lists

  console.log(JSON.stringify(json));
}

function perSurvivor(
  k: keyof (typeof json.survivors)["11111111-1111-1111-1111-111111111111"],
  i: number,
  c: Challenge
) {
  json.survivors["11111111-1111-1111-1111-111111111111"][k].attributes.MOV =
    c.survivors[i].stats.movement + 5;
  json.survivors["11111111-1111-1111-1111-111111111111"][k].attributes.STR =
    c.survivors[i].stats.strength;
  json.survivors["11111111-1111-1111-1111-111111111111"][k].attributes.EVA =
    c.survivors[i].stats.evasion;
  json.survivors["11111111-1111-1111-1111-111111111111"][k].attributes.ACC =
    c.survivors[i].stats.accuracy;
  json.survivors["11111111-1111-1111-1111-111111111111"][k].attributes.LCK =
    c.survivors[i].stats.luck;
  json.survivors["11111111-1111-1111-1111-111111111111"][k].attributes.SPD =
    c.survivors[i].stats.speed;

  json.survivors["11111111-1111-1111-1111-111111111111"][k].xp =
    c.survivors[i].stats.xp;
  json.survivors["11111111-1111-1111-1111-111111111111"][k].courage =
    c.survivors[i].stats.courage;
  json.survivors["11111111-1111-1111-1111-111111111111"][k].understanding =
    c.survivors[i].stats.understanding;

  if (c.survivors[i].stats.choose > 0) {
    json.survivors["11111111-1111-1111-1111-111111111111"][k].notes +=
      "Gain a stat of your choice, ";
  }
  if (c.survivors[i].stats.fa > 0) {
    json.survivors["11111111-1111-1111-1111-111111111111"][
      k
    ].notes += `Gain ${c.survivors[i].stats.fa} Fighting Arts, `;
  }
  if (c.survivors[i].stats.sfa > 0) {
    json.survivors["11111111-1111-1111-1111-111111111111"][
      k
    ].notes += `Gain ${c.survivors[i].stats.sfa} Secret Fighting Arts, `;
  }
  if (c.survivors[i].stats.disorders > 0) {
    json.survivors["11111111-1111-1111-1111-111111111111"][
      k
    ].notes += `Gain ${c.survivors[i].stats.disorders} Disorders, `;
  }
  if (c.survivors[i].abilities.length > 0) {
    json.survivors["11111111-1111-1111-1111-111111111111"][
      k
    ].notes += `Abilities: ${c.survivors[i].abilities}`;
  }

  json.survivors["11111111-1111-1111-1111-111111111111"][k].name =
    c.survivors[i].title;

  json.survivors["11111111-1111-1111-1111-111111111111"][k].insanity = {
    value: c.survivors[i].stats.insanity,
    light: false,
  };
}
